@startuml

header ReNaTa Document Design 2023
title Profile Functions

actor user
participant ReNaTa
participant backend

note left: User can view and edit their profile information such as name, email, and password

user->ReNaTa: request to update profile information
note right: Profile form: \nName, \nEmail, \nPassword, \nProfile Image

user->ReNaTa: input profile form
ReNaTa->ReNaTa: check the form input fields, \nuse checker for the handling
backend<-ReNaTa: sends the form input

alt profile image included
    backend->backend: save profile image 
    note right:use cloud storage,\nuse the profile image by creating the url
end

backend->backend: update profile information 
alt profile information updated successfully
    backend->ReNaTa: sends notification success and status code 200
    note right: status code 200 for success
    user<-ReNaTa: successfully update notification
else profile information failed to update
    backend->ReNaTa: sends notification failed
    note right: status code 400(if the user bad request) or \n 500(if there's problem with the backend)
    user<-ReNaTa: sends notification failed
end

@enduml
