@startuml

header ReNaTa Document Design 2023
title User Reset Password

actor user
participant ReNaTa
participant backend

user->ReNaTa: request reset password 

user<-ReNaTa: response reset password form 

note right: Reset form: \nold password, \nnew password

loop until valid old password
    alt user input valid old password
        user->ReNaTa: input reset password form
        backend<-ReNaTa: sends the form input
        alt old password confirmed
            backend->backend: verify old password 
            alt valid old password
                backend->backend: replace password\nwith newer password input
                backend->ReNaTa: sends the notification success \nupdate password 
                user<-ReNaTa: successfully update \nnotification password
            else invalid old password
                note right: Error handling: return 400 Bad Request status code
                backend->ReNaTa: sends notification to failed
                user<-ReNaTa: sends notification failed
                note right: loop destroyed after 3 times attempt
            end
        else old password not confirmed
            note right: Error handling:\n return 400 Bad Request status code
            backend->ReNaTa: sends notification to failed
            user<-ReNaTa: sends notification failed
            note right: loop destroyed after 3 times attempt
        end
    else user failed validating old password 
        note right: Error handling:\n return 400 Bad Request status code
        backend->ReNaTa: sends notification to failed
        user<-ReNaTa: sends notification failed
        note right: loop destroyed after 3 times attempt
    end
end

@enduml